name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  install:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: vmactions/freebsd-vm@v0
        with:
          copyback: false
          release: "13.0"
          run: |
            setenv DESTDIR `mktemp -d`
            make install
